<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'lessc'                                  => __DIR__ . '/src/Less/lessc.inc.php',
    'lessc_parser'                           => __DIR__ . '/src/Less/lessc.inc.php',
    'lessc_formatter_classic'                => __DIR__ . '/src/Less/lessc.inc.php',
    'lessc_formatter_compressed'             => __DIR__ . '/src/Less/lessc.inc.php',
    'lessc_formatter_lessjs'                 => __DIR__ . '/src/Less/lessc.inc.php',
    'easyparse'                              => __DIR__ . '/src/Less/lessify.inc.php',
    'tagparse'                               => __DIR__ . '/src/Less/lessify.inc.php',
    'nodecounter'                            => __DIR__ . '/src/Less/lessify.inc.php',
    'lessify'                                => __DIR__ . '/src/Less/lessify.inc.php',
    'ApiTest'                                => __DIR__ . '/src/Less/tests/ApiTest.php',
    'InputTest'                              => __DIR__ . '/src/Less/tests/InputTest.php',
    'lesscNormalized'                        => __DIR__ . '/src/Less/tests/sort.php',
    'SortingFormatter'                       => __DIR__ . '/src/Less/tests/sort.php',
);
