<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('EVA. '. $this->translate('ASSES FIRST'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/asses-favicon.gif'))
                        
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						?>
		
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
		<link href="<?php echo $this->basePath($this->less('less/style.less')) ?>" media="screen" rel="stylesheet" type="text/css">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/asses-logo.jpg') ?>" alt="Asses First"/>&nbsp;<h1><?php echo $this->translate('Asses First') ?></h1></a>
					
				</div>
				
				<ul class="nav nav-pills">
							  <li class="nav-icon"><a class="ico-1" href="<?php echo $this->url('home') ?>"></a></li>
							  <li class="nav-icon"><a class="ico-2"href="<?php echo $this->url('home') ?>"></a></li>
				</ul>
				
                <div class="collapse navbar-collapse col-md-2">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Lancer une évaluation') ?></a></li>
						<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Voir des résultats') ?></a></li>
						<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Aller plus loin...') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
				
				<div class="col-md-4">
				
					<input type="text" class="form-control bt-search" placeholder="Search...">
					
					<ul class="nav nav-pills col-md-3 col-md-offset-2">
								  <li class="nav2-icon"><a class="ico-3" href="<?php echo $this->url('home') ?>"></a></li>
								  <li class="nav2-icon"><a class="ico-4"href="<?php echo $this->url('home') ?>"></a></li>
					</ul>
				
				</div>
            </div>
        </nav>
        <div class="container">
			<div class="row">	
				<div class="col-md-3">
					<aside>
					
						<p>lorem</p><p>lorem</p>
					
					</aside>
				</div>
				<div class="col-md-9">
					<div class="main"><?php echo $this->content; ?></div>
				</div>
			</div>
				<hr>
			<div class="row">
				<footer>
					<p>&copy; <?php echo date('Y') ?> - <?php echo $this->translate('By ASSES FIRST') ?></p>
				</footer>
			</div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
