<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('EVA. '. $this->translate('ASSES FIRST'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/asses-favicon.gif'))
                        
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						// ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/whhg.css')
						?>
		
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
		<link href="<?php echo $this->basePath($this->less('less/style.less')) ?>" media="screen" rel="stylesheet" type="text/css">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/asses-logo.jpg') ?>" alt="Asses First"/>&nbsp;<h1><?php echo $this->translate('Asses First') ?></h1></a>
					
				</div>
				
				<ul class="nav nav-pills">
							  <li class="nav-icon"><a class="ico-1" href="<?php echo $this->url('home') ?>"></a></li>
							  <li class="nav-icon"><a class="ico-2"href="<?php echo $this->url('home') ?>"></a></li>
				</ul>
				
                <div class="collapse navbar-collapse col-md-2">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Lancer une évaluation') ?></a></li>
						<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Voir des résultats') ?></a></li>
						<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Aller plus loin...') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
				
				<div class="col-md-4">
				
					<input type="text" class="form-control bt-search" placeholder="Search...">
					
					<ul class="nav nav-pills col-md-3 col-md-offset-2">
								  <li class="nav2-icon"><a class="ico-3" href="<?php echo $this->url('home') ?>"></a></li>
								  <li class="nav2-icon"><a class="ico-4"href="<?php echo $this->url('home') ?>"></a></li>
					</ul>
				
				</div>
            </div>
        </nav>
        <div class="container">
			<div class="row">	
				<div class="col-md-3">
					<aside>
					
						<div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-3"><img src="<?php echo $this->basePath('img/pic6.jpg') ?>" style="width: 100%" alt="Profil"/></div>
                    <div class="col-md-9"><strong class="panel-title">David BERNARD</strong><br /><span>1267</span></div>
                </div>
            </div>
            <div class="panel-body">
                <p><a class="btn btn-block btn-success"><i class="icon-user"></i>  Créer un évalué</a></p>
                <p><a class="btn btn-block btn-default"><i class="icon-groups-friends"></i> Importer des évalués</a></p>
            </div>
            <form role="form" style="margin-bottom: 20px">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#eval" class="">Evaluations</a></h4>
                        </div>
                        <div id="eval" class="panel-collapse in" style="height: auto;">
                            <div class="panel-body row">
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> PSV20 <span class="badge pull-right">924</span> </label>
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> MF20 <span class="badge pull-right">42</span> </label>
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> GF40 <span class="badge pull-right">12</span> </label>
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> MNG360 <span class="badge pull-right">13</span> </label>
                                <hr />
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> Dernières lancées </label>
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> Dernières complétées  </label>
                                <hr />
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> Les miennes <span class="badge pull-right">1274</span> </label>
                                <label class="col-md-12"> <input type="checkbox" name="eval[]"> Cellules de Simon Baron <span class="badge pull-right">27</span> </label>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#fonction" class="">Fonction</a></h4>
                        </div>
                        <div id="fonction" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#poste" class="">Poste</a></h4>
                        </div>
                        <div id="poste" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#secteur" class="">Secteur</a></h4>
                        </div>
                        <div id="secteur" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#entreprise" class="">Entreprise</a></h4>
                        </div>
                        <div id="entreprise" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#experience" class="">Expérience</a></h4>
                        </div>
                        <div id="experience" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#niveaures" class="">Niveau de responsabilté</a></h4>
                        </div>
                        <div id="niveaures" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#management" class="">Management</a></h4>
                        </div>
                        <div id="management" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#etude" class="">Niveau d'étude</a></h4>
                        </div>
                        <div id="etude" class="panel-collapse collapse" style="height: auto;">
                            <div class="panel-body">
                                Repellendus quia eligendi quae earum voluptate rerum sed recusandae consectetur saepe sed.
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
					
					</aside>
				</div>
				<div class="col-md-9">
					<div class="main"><?php echo $this->content; ?></div>
				</div>
			</div>
				<hr>
			<div class="row">
				<footer>
					<p>&copy; <?php echo date('Y') ?> - <?php echo $this->translate('By ASSES FIRST') ?></p>
				</footer>
			</div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>