

<div class="row">
	<div class="col-md-3">
		<aside>
			<div class="profile">
				<div class="img-profile">
					<img class="img-responsive" src="<?php echo $this->basePath('img/pic6.jpg') ?>" alt="manager profile"/>
				</div>
				<div class="info-profile">
					<h4><?php echo $this->translate('david') ?> <span><?php echo $this->translate('bernard') ?></span></h4>
					<h6>1267 crédits</h6>
				</div>
			</div>
			<div class="button-wrapper">
				<button type="button" class="btn btn-default btn-block bt-eva">Ajouter une évaluation</button>
				<button type="button" class="btn btn-default btn-block bt-msg">Envoyer un message</button>
			</div>
			<div class="group-wrapper">
				<ul class="list-group">
				  <li class="list-group-item title-list">
					<span class="badge">8</span>
					Ses groupes 
				  </li>
				  <li class="list-group-item">
					<span class="badge">42</span>
					<span class="glyphicon glyphicon-send"></span> Les Winners
				  </li>
				  <li class="list-group-item">
					<span class="badge">16</span>
					<span class="glyphicon glyphicon-leaf"></span> AssessFirst Dream Team
				  </li>
				  <li class="list-group-item">
					<span class="badge">5</span>
					<span class="glyphicon glyphicon-link"></span> Big5 CoDir
				  </li>
				  <li class="list-group-item group-hide">
					  <div class="panel-group" id="accordion">
						  <div class="panel panel-default">
							<div class="panel-heading">
								<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
									Voir tous les groupes
								</a>
							</div>
							<div id="collapseOne" class="panel-collapse collapsing">
							  <div class="panel-body">
								<ul class="list-group">
								  <li class="list-group-item">
									<span class="badge">42</span>
									<span class="glyphicon glyphicon-send"></span> Les Winners
								  </li>
								  <li class="list-group-item">
									<span class="badge">16</span>
									<span class="glyphicon glyphicon-leaf"></span> AssessFirst Dream Team
								  </li>
								  <li class="list-group-item">
									<span class="badge">5</span>
									<span class="glyphicon glyphicon-link"></span> Big5 CoDir
								  </li>
								</ul>
							  </div>
							</div>
						  </div>
					   </div>
				  </li> 				  
				</ul>
			</div>
			<div class="stat-wrapper">
				<h5>Son état d'avancement</h5>
				<div class="stat">
					<div id="jqxChart" style="width: 300px; height: 300px; position: relative; left: 0px;top: 0px;">
					</div>
					
					<a class="" href="<?php echo $this->url('home') ?>">Envoyer un email de rappel</a></li>
				</div>
			</div>
			<div class="cnx-wrapper">
				<h5>Sa dernière connexion</h5>
				<div class="cnx">
					<p><?php echo $this->translate('11 Avril 2013') ?> à <?php echo $this->translate('11:11:11') ?></p>
				</div>
			</div>
		</aside>
	</div>
	<div class="col-md-9">
		
		<div class="main">
			<div class="col-md-8">
				<div class="profile">
					<div class="info-profile">
						<h3><?php echo $this->translate('alexandre') ?> <span><?php echo $this->translate('collignon') ?></span></h3>
						<h5><?php echo $this->translate('Head of Sales of AssessFirst (Edition de logiciels)') ?></h5>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<ul class="nav nav-pills">
							  <li class="nav2-icon"><a class="ico-5" href="<?php echo $this->url('home') ?>"></a></li>
							  <li class="nav2-icon"><a class="ico-6"href="<?php echo $this->url('home') ?>"></a></li>
							  <li class="nav2-icon"><a class="ico-7"href="<?php echo $this->url('home') ?>"></a></li>
							  <li class="nav2-icon"><a class="ico-8"href="<?php echo $this->url('home') ?>"></a></li>
				</ul>
			</div>
			
			<div class="col-md-12">
				
			</div>
			
		</div>
		
		<!--<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
				</div>
				<div class="panel-body">
					<p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
					<p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
				</div>
				<div class="panel-body">
					<p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
					<p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
				</div>
				<div class="panel-body">
					<p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
					<p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
				</div>
			</div>
		</div>

	</div>
</div>
<!--<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>-->

<script  type="text/javascript">
            $(document).ready(function() {
            // use static sample data
            var sampleData = [{
            'Title': 'TODO',
                    'Value': 25
            },
            {
            'Title': 'done',
                    'Value': 75
            }];
                    // prepare chart data as an array
                    /*var source =
                     {
                     datatype: "json",
                     datafields: [
                     {name: 'p1'},
                     {name: 'p2'}
                     ],
                     url: 'sampleData.json'
                     };
                     
                     var dataAdapter = new $.jqx.dataAdapter(source,
                     {
                     async: false,
                     autoBind: true,
                     loadError: function(xhr, status, error) {
                     alert('Error loading "' + source.url + '" : ' + error);
                     }
                     }
                     );*/
                    $.jqx._jqxChart.prototype.colorSchemes.push({name: 'myScheme', colors: ['#dd0000', '#00dd00']});
                    // prepare jqxChart settings
                    var jqxChartSettings = {
                    title: "Test jqxChart",
                            description: "(source: statique)",
                            enableAnimations: true,
                            showLegend: false,
                            legendPosition: {left: 520, top: 140, width: 100, height: 100},
                            padding: {left: 5, top: 5, right: 5, bottom: 5},
                            titlePadding: {left: 0, top: 0, right: 0, bottom: 10},
                            //source: dataAdapter,
                            source: sampleData,
                            colorScheme: 'myScheme',
                            seriesGroups:
                            [
                            {
                            type: 'pie',
                                    showLabels: true,
                                    series:
                                    [
                                    {
                                    dataField: 'Value',
                                            displayText: 'Title',
                                            labelRadius: 60,
                                            initialAngle: 0,
                                            radius: 120,
                                            centerOffset: 0,
                                            formatSettings: {sufix: '%', decimalPlaces: 1}
                                    }
                                    ]
                            }
                            ]
                    };
                    // setup the chart
                    $('#jqxChart').jqxChart(jqxChartSettings);
					})
        </script>

